# **Electric Vehicles Charging Stations Infrastructure and Detection**

## **Overview**

The adoption of electric vehicles (EVs) is increasing worldwide, creating a growing demand for reliable charging infrastructure. Proper planning of charging stations is important to ensure accessibility, reduce waiting times, and support sustainable transportation. This project focuses on analyzing charging station data to understand usage patterns and identify areas where infrastructure improvements are needed and to aid drivers in locating reliable charging stations with power and in close range distance.

## **Business Problem and Stakeholders**

The increase in electric vehicles in Kenya has created pressure on charging infrastructure https://www.the-star.co.ke/news/2026-02-11-ev-charging-drives-188-surge-in-kenyas-electricity-use?utm_source=copilot.com.

 Many areas lack sufficient charging stations, while others are underutilized https://techtrendske.co.ke/2025/09/28/kenya-ev-charging-stations-expansion-2030/?utm_source=copilot.com.
 
  This project aims to analyze and predict optimal charging station placement and usage to improve efficiency and accessibility.

At the same time, electric vehicle drivers face challenges in locating nearby charging stations and determining whether those stations are operational and have available power. This creates range anxiety, reduces user confidence, and may slow down the adoption of electric vehicles across the country.A Single Station Cuts Charging Time and Hints at What a Functioning National EV Network Might Finally Look Like https://techtrendske.co.ke/2025/11/19/kenya-ev-fast-charging-network/

The primary stakeholders for this problem are Government; Ministry of Transport and Ministry of Energy, EV charging investors, EV drivers and EV charging companies.The government uses the system for data-driven infrastructure planning, investors identify profitable charging locations, EV companies improve fleet operations and expansion decisions, and EV drivers gain easier access to reliable nearby charging stations.

## **Business Solution and Objectives**

How can charging demand be forecasted using international datasets calibrated with Kenya's EV adoption statistics?
The proposed solution is the development of a smart, data-driven EV charging decision support system that combines geospatial analysis, machine learning, and predictive modeling to improve both infrastructure planning and driver accessibility. 

How can optimization algorithms recommend the best placement of new stations while considering grid reliability and identifying underserved areas for new charging stations?
For infrastructure planning, the project will use spatial data to estimate future EV charging demand across different locations. Supervised machine learning models such as Random Forest, Gradient Boosting or regression techniques will be used to generate a charging demand score for different areas, while clustering algorithms such as K-Means will identify high-demand hotspots and recommend optimal locations for new charging stations. 

How can drivers quickly locate the nearest and most reliable charging stations?
For driver support, the system will incorporate geospatial distance calculations and nearest-neighbor search to identify the closest charging stations, while classification or time-series models will be used to predict station availability and power status based on historical usage patterns, time of day, and day of week.

 Together, these methods will create an integrated system that helps stakeholders make informed infrastructure investment decisions while enabling EV drivers to easily locate nearby and reliable charging stations.

## **Data Understanding**

The primary data for this project was sourced from HuggingFace, https://huggingface.co/datasets/tarekmasryo/global-ev-infra-dataset.

The dataset contains five separate files with descriptions on:
* `charging_stations_world.csv` The global charging stations
* `charging_stations_ml.csv` City level view of charging infrastructure
* `country_summary.csv` Compact country level overview
* `world_summary.csv` Detailed country levele infrastructure profile
* `ev_models.csv` Electric vehicle models and attributes

### Main file — `charging_stations_world.csv` and `charging_stations_ml.csv`
One row per charging site (**11 columns**):  

- `id` (int)- unique site ID  
- `name` (str)- site name  
- `city` (str) — city name  
- `country_code` - each country's code  
- `state_province` (str) — province names 
- `latitude`, `longitude` - location of stations
- `ports` (int)- number of charging points  
- `power_kw` (float) - maximum site power (kW)  
- `power_class` (str)- derived from `power_kw` thresholds  
- `is_fast_dc` (bool)- `true` if `power_kw ≥ 50`

In [1]:
import pandas as pd

global_stations_df= pd.read_csv('./Data/charging_station_ml.csv')
global_stations_df.head()

,country_code,state_province,city,latitude,longitude,station_count,port_count,fast_station_count,fast_port_count,fast_station_share,fast_port_share,max_power_kw,median_power_kw,dc_fast_station_count,dc_ultra_station_count,has_fast_dc,has_ultra_dc
0,AD,Andorra la Vella,Andorra la Vella,42.506880,1.527992,2,4,0,0,0.0,0.0,22.0,22.0,0,0,0,0
1,AD,Andorra la Vella,Santa Coloma,42.496959,1.500966,1,2,0,0,0.0,0.0,22.0,22.0,0,0,0,0
2,AD,Canillo,Canillo,42.565901,1.598916,1,2,0,0,0.0,0.0,22.0,22.0,0,0,0,0
3,AD,Canillo,Soldeu,42.577997,1.663842,1,2,0,0,0.0,0.0,4.0,4.0,0,0,0,0
4,AD,Encamp,Encamp,42.535057,1.581334,2,3,0,0,0.0,0.0,22.0,14.7,0,0,0,0

In [2]:
global_stations_df['city'].value_counts

<bound method IndexOpsMixin.value_counts of 0              Andorra la Vella
1                  Santa Coloma
2                       Canillo
3                        Soldeu
4                        Encamp
                  ...
58637              Vanrhynsdorp
58638                Willowmore
58639              Wolwefontein
58640                 Worcester
58641    Gqeberha, Eastern Cape
Name: city, Length: 58642, dtype: object>

In [3]:
global_stations_df['state_province'].value_counts

<bound method IndexOpsMixin.value_counts of 0        Andorra la Vella
1        Andorra la Vella
2                 Canillo
3                 Canillo
4                  Encamp
               ...
58637        Western Cape
58638        Western Cape
58639        Western Cape
58640        Western Cape
58641        eastern cape
Name: state_province, Length: 58642, dtype: object>

In [4]:
global_stations_df.columns

Index(['country_code', 'state_province', 'city', 'latitude', 'longitude',
       'station_count', 'port_count', 'fast_station_count', 'fast_port_count',
       'fast_station_share', 'fast_port_share', 'max_power_kw',
       'median_power_kw', 'dc_fast_station_count', 'dc_ultra_station_count',
       'has_fast_dc', 'has_ultra_dc'],
      dtype='object')

This dataset shows the global charging infrastructure.

In [5]:
city_stations_df= pd.read_csv('./Data/charging_station_ml.csv')
city_stations_df.head()

,country_code,state_province,city,latitude,longitude,station_count,port_count,fast_station_count,fast_port_count,fast_station_share,fast_port_share,max_power_kw,median_power_kw,dc_fast_station_count,dc_ultra_station_count,has_fast_dc,has_ultra_dc
0,AD,Andorra la Vella,Andorra la Vella,42.506880,1.527992,2,4,0,0,0.0,0.0,22.0,22.0,0,0,0,0
1,AD,Andorra la Vella,Santa Coloma,42.496959,1.500966,1,2,0,0,0.0,0.0,22.0,22.0,0,0,0,0
2,AD,Canillo,Canillo,42.565901,1.598916,1,2,0,0,0.0,0.0,22.0,22.0,0,0,0,0
3,AD,Canillo,Soldeu,42.577997,1.663842,1,2,0,0,0.0,0.0,4.0,4.0,0,0,0,0
4,AD,Encamp,Encamp,42.535057,1.581334,2,3,0,0,0.0,0.0,22.0,14.7,0,0,0,0

In [6]:
city_stations_df.columns

Index(['country_code', 'state_province', 'city', 'latitude', 'longitude',
       'station_count', 'port_count', 'fast_station_count', 'fast_port_count',
       'fast_station_share', 'fast_port_share', 'max_power_kw',
       'median_power_kw', 'dc_fast_station_count', 'dc_ultra_station_count',
       'has_fast_dc', 'has_ultra_dc'],
      dtype='object')

This dataset shows charging infrastructure at city levels.

In [7]:
country_stations_df = pd.read_csv('./Data/country_summary.csv')
country_stations_df.head()

,country_code,country,station_count,port_count,fast_station_share,fast_port_share
0,AD,Andorra,96,259,0.062500,0.138996
1,AE,United Arab Emirates,131,346,0.175573,0.410405
2,AF,Afghanistan,1,1,0.000000,0.000000
3,AL,Albania,15,16,0.600000,0.562500
4,AM,Armenia,4,6,0.250000,0.166667

This dataset shows a compact summary of the charging stations at country levels.

In [8]:
country_stations_df.columns

Index(['country_code', 'country', 'station_count', 'port_count',
       'fast_station_share', 'fast_port_share'],
      dtype='object')

In [9]:
ev_make_df= pd.read_csv('./Data/ev_models.csv')
ev_make_df.head()

,make,model,market_regions,powertrain,first_year,body_style,origin_country,age_2025
0,Tesla,Model S,Global (US/EU/UK/ME),BEV,2012,Sedan,US,13
1,Tesla,Model 3,Global (US/EU/UK/ME/CN),BEV,2017,Sedan,US,8
2,Tesla,Model X,Global (US/EU/UK/ME),BEV,2015,SUV,US,10
3,Tesla,Model Y,Global (US/EU/UK/ME/CN),BEV,2020,SUV,US,5
4,Tesla,Cybertruck,US (limited),BEV,2023,Pickup,US,2

This dataset shows analysis on EV makes.

In [10]:
ev_models_df= pd.read_csv('./Data/world_summary.csv')
ev_models_df.head()

,country_code,country,station_count,port_count,fast_station_count,fast_port_count,fast_station_share,fast_port_share,max_power_kw,median_power_kw,dc_fast_station_count,dc_ultra_station_count
0,AD,Andorra,96,259,6,36,0.062500,0.138996,300.0,22.0,6,2
1,AE,United Arab Emirates,131,346,23,142,0.175573,0.410405,250.0,22.0,23,16
2,AF,Afghanistan,1,1,0,0,0.000000,0.000000,22.0,22.0,0,0
3,AL,Albania,15,16,9,9,0.600000,0.562500,180.0,120.0,9,1
4,AM,Armenia,4,6,1,1,0.250000,0.166667,150.0,86.0,1,1

In [11]:
ev_models_df.columns

Index(['country_code', 'country', 'station_count', 'port_count',
       'fast_station_count', 'fast_port_count', 'fast_station_share',
       'fast_port_share', 'max_power_kw', 'median_power_kw',
       'dc_fast_station_count', 'dc_ultra_station_count'],
      dtype='object')

This dataset shows info on EV attributes.

In [12]:
df_1 = pd.read_csv('./Data/detailed_ev_charging_stations.csv')
df_1.head()

,Station ID,Latitude,Longitude,Address,Charger Type,Cost (USD/kWh),Availability,Distance to City (km),Usage Stats (avg users/day),Station Operator,Charging Capacity (kW),Connector Types,Installation Year,Renewable Energy Source,Reviews (Rating),Parking Spots,Maintenance Frequency
0,EVS00001,-33.400998,77.974972,"4826 Random Rd, City 98, Country",AC Level 2,0.27,9:00-18:00,4.95,35,EVgo,350,"CCS, CHAdeMO",2013,Yes,4.0,7,Annually
1,EVS00002,37.861857,-122.490299,"8970 San Francisco Ave, San Francisco",DC Fast Charger,0.19,24/7,4.96,83,EVgo,350,"Tesla, Type 2",2010,Yes,3.9,2,Monthly
2,EVS00003,13.776092,100.412776,"5974 Bangkok Ave, Bangkok",AC Level 2,0.48,6:00-22:00,8.54,24,ChargePoint,50,"Type 2, CCS",2019,No,3.6,9,Annually
3,EVS00004,43.628250,-79.468935,"6995 Toronto Ave, Toronto",AC Level 1,0.41,9:00-18:00,13.28,70,Greenlots,350,Type 2,2010,Yes,4.2,7,Monthly
4,EVS00005,19.119865,72.913368,"5704 Mumbai Ave, Mumbai",AC Level 2,0.11,9:00-18:00,9.76,19,EVgo,350,CCS,2015,Yes,3.7,6,Annually

In [13]:
df_2= pd.read_csv('./Data/Electric_Vehicle_Population_Data.csv')
df_2.head()

,VIN (1-10),County,City,State,Postal Code,Model Year,Make,Model,Electric Vehicle Type,Clean Alternative Fuel Vehicle (CAFV) Eligibility,Electric Range,Base MSRP,Legislative District,DOL Vehicle ID,Vehicle Location,Electric Utility,2020 Census Tract
0,1N4BZ0CP5G,King,Seattle,WA,98125.0,2016,NISSAN,LEAF,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,84.0,0.0,46.0,349455557,POINT (-122.30253 47.72656),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),5.303300e+10
1,KNDJX3AEXG,King,Renton,WA,98058.0,2016,KIA,SOUL,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,93.0,31950.0,11.0,210641315,POINT (-122.08747 47.4466),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),5.303303e+10
2,5YJ3E1EB2J,King,Seattle,WA,98115.0,2018,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,215.0,0.0,43.0,171417494,POINT (-122.31676 47.68156),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),5.303300e+10
3,1C4RJXN64R,Kitsap,Bremerton,WA,98312.0,2024,JEEP,WRANGLER,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,21.0,0.0,26.0,262542927,POINT (-122.65223 47.57192),PUGET SOUND ENERGY INC,5.303508e+10
4,5YJ3E1EB1J,Thurston,Olympia,WA,98512.0,2018,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,215.0,0.0,35.0,110432815,POINT (-122.9131 47.01359),PUGET SOUND ENERGY INC,5.306701e+10

In [14]:
df_3= pd.read_csv('./Data/ev_stations_2025.csv')
df_3.head()

,id,title,address,town,state,postcode,country,lat,lon,operator,status,num_connectors,connector_types,date_added
0,462769,Electra - Wambrechies - Volfoni,81 Av. Clément Ader,Wambrechies,NaN,59118,FR,50.685653,3.062410,Electra,Operational,2,CCS (Type 2)|Type 2 (Socket Only),2025-11-02 09:58:00+00:00
1,462768,Electra - Tourcoing - Action,185 rue du Touquet,Tourcoing,NaN,59200,FR,50.723171,3.180636,Electra,Operational,3,CCS (Type 2)|CHAdeMO|Type 2 (Socket Only),2025-11-02 09:55:00+00:00
2,462767,Electra - Bondues - Sure Hotel by Best Western...,3 Av. Henri Becquerel,Bondues,NaN,59910,FR,50.722535,3.129496,Electra,Operational,2,CCS (Type 2)|Type 2 (Socket Only),2025-11-02 09:50:00+00:00
3,462766,Electra - Bousbecque - Intermarché,Rue Auger,Bousbecque,NaN,59166,FR,50.770139,3.083454,Electra,Operational,2,CCS (Type 2)|Type 2 (Socket Only),2025-11-02 09:46:00+00:00
4,462765,Electra - Halluin - Intermarché,Boulevard de Roncq,Halluin,NaN,59250,FR,50.769938,3.124030,Electra,Operational,2,CCS (Type 2)|Type 2 (Socket Only),2025-11-02 09:42:00+00:00

In [15]:
df_4= pd.read_csv('./Data/kenya_ev_charging_stations_sample.csv')
df_4.head()

  County/City           Station Name Charger Type Connector Types
0     Nairobi           Sarit Centre      AC + DC  Type2, CHAdeMO
1     Nairobi        Two Rivers Mall           AC           Type2
2     Nairobi  Village Market Gigiri           AC           Type2
3     Nairobi   UNGA House Westlands           AC           Type2
4     Nairobi  KCB Towers Upper Hill           AC           Type2

In [16]:
df_5 = pd.read_csv('./Data/kenya-population-distibution-2019-census.csv')
df_5.head()

       County       Total       Male     Female Intersex
0       KENYA  14,831,700  7,352,134  7,478,883      683
1     Mombasa   1,208,333    610,257    598,046       30
2       Kwale     126,431     62,395     64,031        5
3      Kilifi     393,888    191,324    202,558        6
4  Tana River      75,722     37,854     37,867        1

In [19]:
df_6= pd.read_excel('./Data/ken_adminboundaries_tabulardata.xlsx')
df_6.tail(10)

,OBJECTID *,Shape *,admin2Name_en,admin2Pcode,admin2RefName,admin2AltName1_en,admin2AltName2_en,admin1Name_en,admin1Pcode,admin0Name_en,admin0Pcode,date,validOn,validTo,Shape_Length,Shape_Area
280,281,Polygon,Wajir East,KE008034,<Null>,<Null>,<Null>,Wajir,KE008,Kenya,KE,2017-11-03,2018-06-07,<Null>,2.983208,0.347874
281,282,Polygon,Wajir North,KE008033,<Null>,<Null>,<Null>,Wajir,KE008,Kenya,KE,2017-11-03,2018-06-07,<Null>,5.250464,0.845903
282,283,Polygon,Wajir South,KE008038,<Null>,<Null>,<Null>,Wajir,KE008,Kenya,KE,2017-11-03,2018-06-07,<Null>,5.308828,1.753522
283,284,Polygon,Wajir West,KE008036,<Null>,<Null>,<Null>,Wajir,KE008,Kenya,KE,2017-11-03,2018-06-07,<Null>,4.060576,0.660316
284,285,Polygon,Webuye East,KE039221,<Null>,<Null>,<Null>,Bungoma,KE039,Kenya,KE,2017-11-03,2018-06-07,<Null>,0.714407,0.013321
285,286,Polygon,Webuye West,KE039222,<Null>,<Null>,<Null>,Bungoma,KE039,Kenya,KE,2017-11-03,2018-06-07,<Null>,1.010876,0.019180
286,287,Polygon,West Mugirango,KE046271,<Null>,<Null>,<Null>,Nyamira,KE046,Kenya,KE,2017-11-03,2018-06-07,<Null>,0.630183,0.014610
287,288,Polygon,Westlands,KE047274,<Null>,<Null>,<Null>,Nairobi,KE047,Kenya,KE,2017-11-03,2018-06-07,<Null>,0.405298,0.005908
288,289,Polygon,Wundanyi,KE006024,<Null>,<Null>,<Null>,Taita Taveta,KE006,Kenya,KE,2017-11-03,2018-06-07,<Null>,1.214526,0.069243
289,290,Polygon,Yatta,KE016076,<Null>,<Null>,<Null>,Machakos,KE016,Kenya,KE,2017-11-03,2018-06-07,<Null>,1.737731,0.086211