# **Electric Vehicles Charging Stations Infrastructure and Detection**

## **Overview**

The adoption of electric vehicles (EVs) is increasing worldwide, creating a growing demand for reliable charging infrastructure. Proper planning of charging stations is important to ensure accessibility, reduce waiting times, and support sustainable transportation. This project focuses on analyzing charging station data to understand usage patterns and identify areas where infrastructure improvements are needed and to aid drivers in locating reliable charging stations with power and in close range distance.

## **Business Problem and Stakeholders**

The increase in electric vehicles in Kenya has created pressure on charging infrastructure https://www.the-star.co.ke/news/2026-02-11-ev-charging-drives-188-surge-in-kenyas-electricity-use?utm_source=copilot.com.

 Many areas lack sufficient charging stations, while others are underutilized https://techtrendske.co.ke/2025/09/28/kenya-ev-charging-stations-expansion-2030/?utm_source=copilot.com.
 
  This project aims to analyze and predict optimal charging station placement and usage to improve efficiency and accessibility.

At the same time, electric vehicle drivers face challenges in locating nearby charging stations and determining whether those stations are operational and have available power. This creates range anxiety, reduces user confidence, and may slow down the adoption of electric vehicles across the country.A Single Station Cuts Charging Time and Hints at What a Functioning National EV Network Might Finally Look Like https://techtrendske.co.ke/2025/11/19/kenya-ev-fast-charging-network/

The primary stakeholders for this problem are Government; Ministry of Transport and Ministry of Energy, EV charging investors, EV drivers and EV charging companies.The government uses the system for data-driven infrastructure planning, investors identify profitable charging locations, EV companies improve fleet operations and expansion decisions, and EV drivers gain easier access to reliable nearby charging stations.

## **Business Solution and Objectives**

How can charging demand be forecasted using international datasets calibrated with Kenya's EV adoption statistics?
The proposed solution is the development of a smart, data-driven EV charging decision support system that combines geospatial analysis, machine learning, and predictive modeling to improve both infrastructure planning and driver accessibility. 

How can optimization algorithms recommend the best placement of new stations while considering grid reliability and identifying underserved areas for new charging stations?
For infrastructure planning, the project will use spatial data to estimate future EV charging demand across different locations. Supervised machine learning models such as Random Forest, Gradient Boosting or regression techniques will be used to generate a charging demand score for different areas, while clustering algorithms such as K-Means will identify high-demand hotspots and recommend optimal locations for new charging stations. 

How can drivers quickly locate the nearest and most reliable charging stations?
For driver support, the system will incorporate geospatial distance calculations and nearest-neighbor search to identify the closest charging stations, while classification or time-series models will be used to predict station availability and power status based on historical usage patterns, time of day, and day of week.

 Together, these methods will create an integrated system that helps stakeholders make informed infrastructure investment decisions while enabling EV drivers to easily locate nearby and reliable charging stations.

## **Data Understanding**

The primary datasets for this project were sourced from HuggingFace, https://huggingface.co/datasets/tarekmasryo/global-ev-infra-dataset,

Kaggle, https://www.kaggle.com/datasets/paulmaluki/kenyapopulationdistibution-2019-censuscsv,

Fundi wa EV, https://www.fundiwaev.co.ke/ev_database and 

OCHA services, https://data.humdata.org/dataset/cod-ab-ken

The datasets utilized in this project are:
* `charging_station.csv` This dataset shows the locations of different charging stations across the world.

* `kenya_ev_charging_stations.csv` This dataset expounds deeper into charging stations in Kenya.

* `kenya-poulation-distribution-2019.csv` This dataset shows population density in different counties across Kenya.

* `ken_adminboundaries_tabulardata.xlsx` This dataset shows details on county boundaries across the country.

In [20]:
import pandas as pd

global_stations_df= pd.read_csv('./Data/charging_station.csv')
global_stations_df.head()

,id,name,city,state_province,country_code,latitude,longitude,ports,power_kw,power_class,is_fast_dc
0,307660,Av. de Tarragona,Andorra,UNKNOWN,AD,42.505254,1.528861,10,300.0,DC_ULTRA_(>=150kW),True
1,301207,Parquing Costa Rodona,Encamp,UNKNOWN,AD,42.537213,1.727014,10,22.0,AC_HIGH_(22-49kW),False
2,301206,Hotel Naudi,Unknown City,UNKNOWN,AD,42.576811,1.666061,1,11.0,AC_L2_(7.5-21kW),False
3,301205,Hotel Piolets Soldeu Centre,Unknown City,UNKNOWN,AD,42.576466,1.667317,1,22.0,AC_HIGH_(22-49kW),False
4,301204,Hotel Serras,Unknown City,UNKNOWN,AD,42.579458,1.659215,3,11.0,AC_L2_(7.5-21kW),False

In [34]:
global_stations_df['city'].value_counts()

city
Unknown City                               22189
London                                      7665
Los Angeles                                 2128
Hammersmith                                 1118
Montréal                                     991
                                           ...
16 London Rd                                   1
Linmere                                        1
Garratt Lane Car Park                          1
Near to the junction with Kingston Road        1
Randburg                                       1
Name: count, Length: 41816, dtype: int64

In [35]:
global_stations_df['state_province'].value_counts()

state_province
UNKNOWN      69998
CA           17528
QC            5579
NY            5259
ON            5012
             ...
Brechin          1
Menstrie         1
Hatfield         1
Gateshead        1
Guateng          1
Name: count, Length: 5989, dtype: int64

In [36]:
global_stations_df.columns

Index(['id', 'name', 'city', 'state_province', 'country_code', 'latitude',
       'longitude', 'ports', 'power_kw', 'power_class', 'is_fast_dc'],
      dtype='object')

This dataset shows the global charging infrastructure.

In [37]:
kenya_stations_df= pd.read_csv('./Data/kenya_ev_charging_stations_sample.csv')
kenya_stations_df.head()

  County/City           Station Name Charger Type Connector Types
0     Nairobi           Sarit Centre      AC + DC  Type2, CHAdeMO
1     Nairobi        Two Rivers Mall           AC           Type2
2     Nairobi  Village Market Gigiri           AC           Type2
3     Nairobi   UNGA House Westlands           AC           Type2
4     Nairobi  KCB Towers Upper Hill           AC           Type2

In [38]:
kenya_stations_df.columns

Index(['County/City', 'Station Name', 'Charger Type', 'Connector Types'], dtype='object')

This dataset shows charging infrastructure at city levels.

In [39]:
kenyan_population_df = pd.read_csv('./Data/kenya-population-distibution-2019-census.csv')
kenyan_population_df.head()

       County       Total       Male     Female Intersex
0       KENYA  14,831,700  7,352,134  7,478,883      683
1     Mombasa   1,208,333    610,257    598,046       30
2       Kwale     126,431     62,395     64,031        5
3      Kilifi     393,888    191,324    202,558        6
4  Tana River      75,722     37,854     37,867        1

This dataset shows a compact summary of the charging stations at country levels.

In [40]:
kenyan_population_df.columns

Index(['County', 'Total', 'Male', 'Female', 'Intersex'], dtype='object')

In [41]:
ken_boundaries_df= pd.read_excel('./Data/ken_adminboundaries_tabulardata.xlsx')
ken_boundaries_df.head()

,OBJECTID *,Shape *,admin2Name_en,admin2Pcode,admin2RefName,admin2AltName1_en,admin2AltName2_en,admin1Name_en,admin1Pcode,admin0Name_en,admin0Pcode,date,validOn,validTo,Shape_Length,Shape_Area
0,1,Polygon,Ainabkoi,KE027144,<Null>,<Null>,<Null>,Uasin Gishu,KE027,Kenya,KE,2017-11-03,2018-06-07,<Null>,1.746986,0.040829
1,2,Polygon,Ainamoi,KE035190,<Null>,<Null>,<Null>,Kericho,KE035,Kenya,KE,2017-11-03,2018-06-07,<Null>,0.917307,0.019957
2,3,Polygon,Aldai,KE029152,<Null>,<Null>,<Null>,Nandi,KE029,Kenya,KE,2017-11-03,2018-06-07,<Null>,1.402637,0.038000
3,4,Polygon,Alego Usonga,KE041234,<Null>,<Null>,<Null>,Siaya,KE041,Kenya,KE,2017-11-03,2018-06-07,<Null>,1.081354,0.049357
4,5,Polygon,Awendo,KE044254,<Null>,<Null>,<Null>,Migori,KE044,Kenya,KE,2017-11-03,2018-06-07,<Null>,0.743915,0.021365

This dataset shows analysis on EV makes.

In [42]:
ken_boundaries_df.columns

Index(['OBJECTID *', 'Shape *', 'admin2Name_en', 'admin2Pcode',
       'admin2RefName', 'admin2AltName1_en', 'admin2AltName2_en',
       'admin1Name_en', 'admin1Pcode', 'admin0Name_en', 'admin0Pcode', 'date',
       'validOn', 'validTo', 'Shape_Length', 'Shape_Area'],
      dtype='object')

This dataset shows info on EV attributes.