In [1]:
import pandas as pd

In [2]:
df_1= pd.read_excel('../Data/LCOE/lcoe-database.xlsx')
df_1.head()

              Levelized cost of electricity database
0                                                NaN
1                                                NaN
2  Author: Govinda R Timilsina, Sr. Economist, De...
3                                                NaN
4  Note: This database is the result of the follo...

In [3]:
df_2= pd.read_csv('../Data/Mini_grids/potential-mini-grid-expansion-project-cost.csv')
df_2.head()

,Entry Number,Substation,Feeder,County,Project_Number,Project Name,Households,Line length by voltage level - km,Unnamed: 8,Unnamed: 9,Total Consumers\n (Year 1),Project Costs US$ Million,Cost per Consumer
0,NaN,NaN,NaN,NaN,NaN,Project Name,NaN,33,11,LV,NaN,NaN,NaN
1,1,MANDERA P/STATION,MANDERA TOWN FEEDER,MANDERA,701.0,MAN-MAN-TOWNSHIP,"3,751",-,7.2,10.5,"3,751",$0.99,$263
2,2,MANDERA P/STATION,MANDERA TOWN FEEDER,MANDERA,702.0,MAN-MAN-BOKOLOW-GARABA QOLEY,164,-,8.6,3.0,164,$0.25,"$1,527"
3,3,MANDERA P/STATION,KHALALIYOW FEEDER,MANDERA,703.0,MAN-MAN-GINGO-MATASAFARA-SAROHINDI,122,-,28.1,6.0,122,$0.64,"$5,286"
4,4,MANDERA P/STATION,KHALALIYOW FEEDER,MANDERA,704.0,MAN-MAN-ARESA,215,-,10.1,1.5,215,$0.24,"$1,109"

In [6]:
import geopandas as gpd

gdf = gpd.read_file("../Data/Roads/roads/Roads/Roads.shp")

gdf.head()

,OBJECTID,RID_8,Length_km,geometry
0,1,A1,892.204644132,MULTILINESTRING Z ((-30859.261 10492745.857 0....
1,2,A1_R,1.00849893272,"LINESTRING Z (27514.120 9988782.604 0.000, 275..."
2,3,A10,970.047258935,MULTILINESTRING Z ((126867.314 10263283.334 0....
3,4,A11,106.498780971,MULTILINESTRING Z ((690937.842 9793980.272 0.0...
4,5,A12,228.075190276,MULTILINESTRING Z ((-45959.560 10051606.770 0....

In [7]:
gdf_1=gpd.read_file('../Data/Population and household/pop_-hh_2016/Pop_ HH_2016/Population_HH_2016.shp')
gdf_1.head()

,OBJECTID_1,SLCODE,FIRST_PROV,MIN_DISTCO,FIRST_DIST,MIN_DIVCOD,FIRST_DIVN,MIN_LOCCOD,FIRST_LOCN,FIRST_SLNA,County,Growth_Rat,Population,HH_2009,Populati_1,HH2016,Shape_Leng,Shape_Area,geometry
0,1,101010101.0,NAIROBI,101.0,NAIROBI WEST,10101.0,DAGORETTI,1010101.0,KAWANGWARE,GATINA,Nairobi,0.06118,45872,15987,69514,24226,6983.942468,1.508052e+06,"POLYGON ((250810.800 9859514.756, 250810.817 9..."
1,2,101010102.0,NAIROBI,101.0,NAIROBI WEST,10101.0,DAGORETTI,1010101.0,KAWANGWARE,KAWANGWARE,Nairobi,0.06118,67414,22262,102158,33736,6477.586086,2.384676e+06,"POLYGON ((249707.081 9858733.360, 249708.322 9..."
2,3,101010201.0,NAIROBI,101.0,NAIROBI WEST,10101.0,DAGORETTI,1010102.0,KENYATTA (GOLF COURSE),KENYATTA GOLF COURSE,Nairobi,0.06118,22816,5987,34575,9073,10817.599007,5.098947e+06,"MULTIPOLYGON (((254391.240 9855167.210, 254391..."
3,4,101010202.0,NAIROBI,101.0,NAIROBI WEST,10101.0,DAGORETTI,1010102.0,KENYATTA (GOLF COURSE),WOODLEY,Nairobi,0.06118,12539,3414,19001,5174,12480.261797,4.419849e+06,"POLYGON ((251099.473 9856292.027, 251125.639 9..."
4,5,101010301.0,NAIROBI,101.0,NAIROBI WEST,10101.0,DAGORETTI,1010103.0,MUTUINI,KIRIGU,Nairobi,0.06118,12208,3694,18500,5598,7524.791103,1.737243e+06,"POLYGON ((244391.440 9857879.178, 244364.724 9..."

In [8]:
gdf_3=gpd.read_file('../Data/Transmission Stations/transmission-stations/Transmission Stations/Transmission_Stations.shp')
gdf_3.head()

,OBJECTID,RCC1,County2,Branch3,Name_IMS11,FDB_Last18,Ownershi23,Street40,Type_Acc42,Manned50,VHF_Radi55,Earthing56,Remote_T57,Programm58,Ripple_C59,Source,geometry
0,1,Juja-Nairobi South,Nairobi South,Komarock - Kayole - Umoja,DANDORA ( 220 / 132 KV),25/03/2014 13:39:36,KPLC,KOMOROCK RD.,MURRAM,NO,NaN,YES,YES,YES,YES,KPLC FDB,POINT (268017.834 9860476.141)
1,2,Kiganjo Mt kenya,Embu,Kamburu,"KAMBURU 132 KV SUBSTATION ( 11,132 / 33,132 KV)",04/07/2014 10:19:05,KPLC & KENGEN,KANGONDE - EMBU ROAD,TARMAC,YES,YES,YES,YES,YES,NO,KPLC FDB,POINT (353715.479 9910923.754)
2,3,Juja-Nairobi South,Machakos,Kivaa,KINDARUMA SUB STATION ( 11 / 132 KV),25/03/2014 13:41:23,KPLC & KENGEN,KINDARUMA ROAD,TARMAC,YES,YES,YES,YES,NO,NO,KPLC FDB,POINT (367936.261 9910405.772)
3,4,Juja-Nairobi South,Nairobi South,Industrial Area - Embakasi,EMBAKASI ( 220 / 66 KV),25/02/2016 08:33:42,KPLC,OFF MOMBASA RD.,TARMAC,YES,YES,YES,NO,NO,YES,KPLC FDB,POINT (263416.241 9851775.344)
4,5,Juja-Nairobi North,Nairobi North,Dandora - Kariobangi - Githurai,"JUJA SUBSTATION ( 132 / 132,66 KV)",17/06/2014 18:46:22,KPLC,JUJA RD.,TARMAC,YES,NO,YES,YES,YES,YES,KPLC FDB,POINT (266944.384 9861228.596)

In [10]:
df_3= pd.read_csv('../Data/charging_station.csv')
df_3.head()

,id,name,city,state_province,country_code,latitude,longitude,ports,power_kw,power_class,is_fast_dc
0,307660,Av. de Tarragona,Andorra,UNKNOWN,AD,42.505254,1.528861,10,300.0,DC_ULTRA_(>=150kW),True
1,301207,Parquing Costa Rodona,Encamp,UNKNOWN,AD,42.537213,1.727014,10,22.0,AC_HIGH_(22-49kW),False
2,301206,Hotel Naudi,Unknown City,UNKNOWN,AD,42.576811,1.666061,1,11.0,AC_L2_(7.5-21kW),False
3,301205,Hotel Piolets Soldeu Centre,Unknown City,UNKNOWN,AD,42.576466,1.667317,1,22.0,AC_HIGH_(22-49kW),False
4,301204,Hotel Serras,Unknown City,UNKNOWN,AD,42.579458,1.659215,3,11.0,AC_L2_(7.5-21kW),False

In [13]:
df_4= pd.read_csv('../Data/kenya_ev_charging_stations_sample.csv')
df_4.head(10)

  County/City              Station Name Charger Type Connector Types
0     Nairobi              Sarit Centre      AC + DC  Type2, CHAdeMO
1     Nairobi           Two Rivers Mall           AC           Type2
2     Nairobi     Village Market Gigiri           AC           Type2
3     Nairobi      UNGA House Westlands           AC           Type2
4     Nairobi     KCB Towers Upper Hill           AC           Type2
5     Nairobi  Britam Towers Upper Hill           AC           Type2
6     Nairobi       Movenpick Westlands           AC           Type2
7     Nairobi               Stima Plaza        AC/DC           Mixed
8     Nairobi              Ruaraka KPLC        AC/DC           Mixed
9      Nakuru             Westside Mall           AC           Type2

In [15]:
df_5= pd.read_csv('../Data/kenya-population-distibution-2019-census.csv')
df_5.head()

       County       Total       Male     Female Intersex
0       KENYA  14,831,700  7,352,134  7,478,883      683
1     Mombasa   1,208,333    610,257    598,046       30
2       Kwale     126,431     62,395     64,031        5
3      Kilifi     393,888    191,324    202,558        6
4  Tana River      75,722     37,854     37,867        1

In [16]:
df_6=pd.read_excel('../Data/ken_adminboundaries_tabulardata.xlsx')
df_6.head()

,OBJECTID *,Shape *,admin2Name_en,admin2Pcode,admin2RefName,admin2AltName1_en,admin2AltName2_en,admin1Name_en,admin1Pcode,admin0Name_en,admin0Pcode,date,validOn,validTo,Shape_Length,Shape_Area
0,1,Polygon,Ainabkoi,KE027144,<Null>,<Null>,<Null>,Uasin Gishu,KE027,Kenya,KE,2017-11-03,2018-06-07,<Null>,1.746986,0.040829
1,2,Polygon,Ainamoi,KE035190,<Null>,<Null>,<Null>,Kericho,KE035,Kenya,KE,2017-11-03,2018-06-07,<Null>,0.917307,0.019957
2,3,Polygon,Aldai,KE029152,<Null>,<Null>,<Null>,Nandi,KE029,Kenya,KE,2017-11-03,2018-06-07,<Null>,1.402637,0.038000
3,4,Polygon,Alego Usonga,KE041234,<Null>,<Null>,<Null>,Siaya,KE041,Kenya,KE,2017-11-03,2018-06-07,<Null>,1.081354,0.049357
4,5,Polygon,Awendo,KE044254,<Null>,<Null>,<Null>,Migori,KE044,Kenya,KE,2017-11-03,2018-06-07,<Null>,0.743915,0.021365