# **EV Charging Station Optimization in Kenya**

In [1]:
import pandas as pd

In [7]:
#Loading the data
df = pd.read_csv('charging_station.csv')
df.head()

,id,name,city,state_province,country_code,latitude,longitude,ports,power_kw,power_class,is_fast_dc
0,307660,Av. de Tarragona,Andorra,UNKNOWN,AD,42.505254,1.528861,10,300.0,DC_ULTRA_(>=150kW),True
1,301207,Parquing Costa Rodona,Encamp,UNKNOWN,AD,42.537213,1.727014,10,22.0,AC_HIGH_(22-49kW),False
2,301206,Hotel Naudi,Unknown City,UNKNOWN,AD,42.576811,1.666061,1,11.0,AC_L2_(7.5-21kW),False
3,301205,Hotel Piolets Soldeu Centre,Unknown City,UNKNOWN,AD,42.576466,1.667317,1,22.0,AC_HIGH_(22-49kW),False
4,301204,Hotel Serras,Unknown City,UNKNOWN,AD,42.579458,1.659215,3,11.0,AC_L2_(7.5-21kW),False

In [8]:
df2= pd.read_csv('country_summary.csv')
df2.head()

,country_code,country,station_count,port_count,fast_station_share,fast_port_share
0,AD,Andorra,96,259,0.062500,0.138996
1,AE,United Arab Emirates,131,346,0.175573,0.410405
2,AF,Afghanistan,1,1,0.000000,0.000000
3,AL,Albania,15,16,0.600000,0.562500
4,AM,Armenia,4,6,0.250000,0.166667

In [9]:
df3= pd.read_csv('world_summary.csv')
df3.head()

,country_code,country,station_count,port_count,fast_station_count,fast_port_count,fast_station_share,fast_port_share,max_power_kw,median_power_kw,dc_fast_station_count,dc_ultra_station_count
0,AD,Andorra,96,259,6,36,0.062500,0.138996,300.0,22.0,6,2
1,AE,United Arab Emirates,131,346,23,142,0.175573,0.410405,250.0,22.0,23,16
2,AF,Afghanistan,1,1,0,0,0.000000,0.000000,22.0,22.0,0,0
3,AL,Albania,15,16,9,9,0.600000,0.562500,180.0,120.0,9,1
4,AM,Armenia,4,6,1,1,0.250000,0.166667,150.0,86.0,1,1

In [10]:
#Filtering the data to Kenya data only
kenya_df = df[df["country_code"] == "KE"].copy()
kenya_df.head()

,id,name,city,state_province,country_code,latitude,longitude,ports,power_kw,power_class,is_fast_dc
128395,267507,City Mall EvChaja,Unknown City,Mombasa,KE,-4.020064,39.720491,1,22.0,AC_HIGH_(22-49kW),False
128396,267505,Waiyaki Way,Unknown City,Nairobi,KE,-1.259614,36.776883,1,22.0,AC_HIGH_(22-49kW),False
128397,194150,Waterfront Mall EvChaja,Unknown City,Nairobi,KE,-1.329425,36.715820,1,22.0,AC_HIGH_(22-49kW),False
128398,194149,Two Rivers Mall EvChaja,Gachie,Nairobi,KE,-1.210229,36.795216,1,11.0,AC_L2_(7.5-21kW),False
128399,189881,Nopea Ride Village Market,Nairobi,Nairobi,KE,-1.227277,36.805228,1,22.0,AC_HIGH_(22-49kW),False