# **EV Charging Station Optimization in Kenya**

In [23]:
import pandas as pd

In [24]:
#Loading the data
charging_station_df = pd.read_csv('../Data/charging_station_ml.csv')
charging_station_df.head()

,country_code,state_province,city,latitude,longitude,station_count,port_count,fast_station_count,fast_port_count,fast_station_share,fast_port_share,max_power_kw,median_power_kw,dc_fast_station_count,dc_ultra_station_count,has_fast_dc,has_ultra_dc
0,AD,Andorra la Vella,Andorra la Vella,42.506880,1.527992,2,4,0,0,0.0,0.0,22.0,22.0,0,0,0,0
1,AD,Andorra la Vella,Santa Coloma,42.496959,1.500966,1,2,0,0,0.0,0.0,22.0,22.0,0,0,0,0
2,AD,Canillo,Canillo,42.565901,1.598916,1,2,0,0,0.0,0.0,22.0,22.0,0,0,0,0
3,AD,Canillo,Soldeu,42.577997,1.663842,1,2,0,0,0.0,0.0,4.0,4.0,0,0,0,0
4,AD,Encamp,Encamp,42.535057,1.581334,2,3,0,0,0.0,0.0,22.0,14.7,0,0,0,0

In [25]:
country_summary_df= pd.read_csv('../Data/country_summary.csv')
country_summary_df.head()

,country_code,country,station_count,port_count,fast_station_share,fast_port_share
0,AD,Andorra,96,259,0.062500,0.138996
1,AE,United Arab Emirates,131,346,0.175573,0.410405
2,AF,Afghanistan,1,1,0.000000,0.000000
3,AL,Albania,15,16,0.600000,0.562500
4,AM,Armenia,4,6,0.250000,0.166667

In [26]:
world_summary_df= pd.read_csv('../Data/world_summary.csv')
world_summary_df.head()

,country_code,country,station_count,port_count,fast_station_count,fast_port_count,fast_station_share,fast_port_share,max_power_kw,median_power_kw,dc_fast_station_count,dc_ultra_station_count
0,AD,Andorra,96,259,6,36,0.062500,0.138996,300.0,22.0,6,2
1,AE,United Arab Emirates,131,346,23,142,0.175573,0.410405,250.0,22.0,23,16
2,AF,Afghanistan,1,1,0,0,0.000000,0.000000,22.0,22.0,0,0
3,AL,Albania,15,16,9,9,0.600000,0.562500,180.0,120.0,9,1
4,AM,Armenia,4,6,1,1,0.250000,0.166667,150.0,86.0,1,1

In [36]:
kenya_ev_stations_df = pd.read_csv('../Data/kenya_ev_charging_stations_sample.csv')
kenya_ev_stations_df.head()

  County/City           Station Name Charger Type Connector Types
0     Nairobi           Sarit Centre      AC + DC  Type2, CHAdeMO
1     Nairobi        Two Rivers Mall           AC           Type2
2     Nairobi  Village Market Gigiri           AC           Type2
3     Nairobi   UNGA House Westlands           AC           Type2
4     Nairobi  KCB Towers Upper Hill           AC           Type2

In [28]:
kenya_population_df = pd.read_csv('../Data/kenya-population-distibution-2019-census.csv')
kenya_population_df.head()

       County       Total       Male     Female Intersex
0       KENYA  14,831,700  7,352,134  7,478,883      683
1     Mombasa   1,208,333    610,257    598,046       30
2       Kwale     126,431     62,395     64,031        5
3      Kilifi     393,888    191,324    202,558        6
4  Tana River      75,722     37,854     37,867        1

In [30]:
kenya_boundaries_df = pd.read_excel('../Data/ken_adminboundaries_tabulardata.xlsx')
kenya_boundaries_df.head()

,OBJECTID *,Shape *,admin2Name_en,admin2Pcode,admin2RefName,admin2AltName1_en,admin2AltName2_en,admin1Name_en,admin1Pcode,admin0Name_en,admin0Pcode,date,validOn,validTo,Shape_Length,Shape_Area
0,1,Polygon,Ainabkoi,KE027144,<Null>,<Null>,<Null>,Uasin Gishu,KE027,Kenya,KE,2017-11-03,2018-06-07,<Null>,1.746986,0.040829
1,2,Polygon,Ainamoi,KE035190,<Null>,<Null>,<Null>,Kericho,KE035,Kenya,KE,2017-11-03,2018-06-07,<Null>,0.917307,0.019957
2,3,Polygon,Aldai,KE029152,<Null>,<Null>,<Null>,Nandi,KE029,Kenya,KE,2017-11-03,2018-06-07,<Null>,1.402637,0.038000
3,4,Polygon,Alego Usonga,KE041234,<Null>,<Null>,<Null>,Siaya,KE041,Kenya,KE,2017-11-03,2018-06-07,<Null>,1.081354,0.049357
4,5,Polygon,Awendo,KE044254,<Null>,<Null>,<Null>,Migori,KE044,Kenya,KE,2017-11-03,2018-06-07,<Null>,0.743915,0.021365

In [32]:
#Filtering the data to Kenya data only
kenya_df = charging_station_df[charging_station_df["country_code"] == "KE"].copy()
kenya_df.head()

,country_code,state_province,city,latitude,longitude,station_count,port_count,fast_station_count,fast_port_count,fast_station_share,fast_port_share,max_power_kw,median_power_kw,dc_fast_station_count,dc_ultra_station_count,has_fast_dc,has_ultra_dc
37850,KE,Mombasa,Unknown City,-4.020064,39.720491,1,1,0,0,0.0,0.0,22.0,22.0,0,0,0,0
37851,KE,Nairobi,Gachie,-1.210229,36.795216,1,1,0,0,0.0,0.0,11.0,11.0,0,0,0,0
37852,KE,Nairobi,Mutuini,-1.319503,36.703528,1,1,0,0,0.0,0.0,11.0,11.0,0,0,0,0
37853,KE,Nairobi,Nairobi,-1.268820,36.828349,7,10,0,0,0.0,0.0,22.0,22.0,0,0,0,0
37854,KE,Nairobi,Unknown City,-1.294520,36.746352,2,2,0,0,0.0,0.0,22.0,22.0,0,0,0,0